### ISSUE TITLE
Task named with plugin handle not listing

### ISSUE THREAD

**Issue by billymedia** [boboldehampsink/taskmanager#5]
Im new to tasks in craft so could be wrong.

When i name my task like so:
PluginHandle_MytaskTask.php 

and i have my create task like so:
`craft()->tasks->createTask('PluginHandle_Mytask', 'my description', array());`

It runs runStep as expected, but doesnt get listed in your plugin.

**Comment by boboldehampsink** [comment]
It only shows up while the task is running. Craft deletes the task when it is done.

**Comment by billymedia** [comment]
Ah right, that would make sense. Cheers.
