### ISSUE TITLE
Ability To Rerun Stuck Tasks

### ISSUE THREAD

**Issue by seanogdev** [boboldehampsink/taskmanager#6]
I've been experiencing issues with the `GeneratePendingTransforms` task after I cleared the transforms index that was previously almost 200k rows. The task usually reindexes about 500-600 before it gives up and gets stuck, but the task itself doesn't fail..

Would it be possible to get an action so that it could rerun all current tasks, so I could rerun the tasks without having to do so manually?

**Comment by boboldehampsink** [comment]
`actionRerunAllFailedTasks` will also check for tasks that have been "hanging" for a certain time.

**Comment by seanogdev** [comment]
Ahh I didnt see that code block, thanks!
